### ISSUE TITLE
error Something went wrong in the model `Phone` with the attribute `user`

### ISSUE THREAD

**Issue by reminute2008** [AugustusCosta/strapi-plugin-facebook-account-kit#1]
When I install the plugin to the project, some issue occurred.

"strapi": "3.0.0-beta.17.6",

First, => yarn add strapi-plugin-facebook-account-kit

yarn develop
yarn run v1.19.1
$ strapi develop
[2019-11-27T11:25:51.296Z] error Something went wrong in the model `Phone` with the attribute `user`
[2019-11-27T11:25:51.297Z] error TypeError: Cannot read property 'nature' of undefined
    at Object.defineAssociations (/server/strapi/new/node_modules/strapi-utils/lib/models.js:440:25)
    at buildRelation (/server/strapi/new/node_modules/strapi-hook-mongoose/lib/mount-models.js:426:15)
    at /server/strapi/new/node_modules/strapi-hook-mongoose/lib/mount-models.js:74:7
    at Array.forEach (<anonymous>)
    at /server/strapi/new/node_modules/strapi-hook-mongoose/lib/mount-models.js:73:26
    at Array.map (<anonymous>)
    at module.exports (/server/strapi/new/node_modules/strapi-hook-mongoose/lib/mount-models.js:14:23)
    at /server/strapi/new/node_modules/strapi-hook-mongoose/lib/index.js:182:16
    at Array.map (<anonymous>)
    at mountPlugins (/server/strapi/new/node_modules/strapi-hook-mongoose/lib/index.js:180:35)
    at /server/strapi/new/node_modules/strapi-hook-mongoose/lib/index.js:132:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AugustusCosta** [comment]
@reminute2008 

Unfortunately the Account Kit is dying. Not worth the effort to update or maintain this plugin = /

https://developers.facebook.com/blog/post/2019/09/09/account-kit-services-no-longer-available-starting-march

I'm working on something similar with Firebase Phone Auth.


But if you are still interested you need to add in User (plugin user-permissions) overwriting within extensions or if you have a plugin folder can be directly there the phone.

./[plugins or extensions]/users-permissions/models/User.settings.json
```
"phone": {
      "unique": true,
      "plugin": "facebook-account-kit",
      "model": "phone",
      "via": "user",
      "configurable": false
    },
```
I did not like much of the necessary modification in User and I believe there must be a better way but during the development of the plugin because of the other projects I had a few hours of Strapi study. Just a newbie.

**Comment by reminute2008** [comment]
@AugustusCosta 

Thanks for ur responding. I'm a newbie too.
Because of ur mention, i just know that Facebook AccountKit will be closed.

Thx again :)
